name: Deploy Application

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
        working-directory: ./client
      - name: Build Client Application
        run: npm run generate
        working-directory: ./client
      - name: Deploy Client Application
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "client/.output/public"
          target: ${{ secrets.CLIENT_PATH }}
          rm: true
