name: Docker test

on:
  pull_request:
    branches: ["*"]

jobs:
  middleware:
    runs-on: ubuntu-latest
    container: nozoyama39/kleines-mypage
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_DATABASE: kleines_mypage_test
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: password
    env:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: kleines_mypage_test
      DB_USERNAME: root
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: ./api
      - name: Composer Install
        run: composer install -n --prefer-dist
        working-directory: ./api
      - name: VCmposer Dump Autoload
        run: composer dump-autoload
        working-directory: ./api
      - name: Generate key
        run: php artisan key:generate
        working-directory: ./api
      - name: Migrate
        run: php artisan migrate
        working-directory: ./api
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
        working-directory: ./api
